name: Deploy to Vercel

on:
  push:
    branches:  [main]

jobs:
  deploy:
    runs-on:  ubuntu-latest

    steps:
      -  name:  Checkout Code
         uses:  actions/checkout@v4

      -  name:  Nodejs Setup
         uses:  actions/setup-node@v4

      -  name:  Install Dependency
         run:  npm install

      -  name:  Build Project
         run:  npm run build

      -  name:  Deploy to vercel
         run:  npx vercel --prod --token=${{ secrets.VERCEL_TOKEN }}                
